import Footer from '@/components/Footer'
import Header from '@/components/Header'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div >
        <Header />
        <div className='mx-auto max-w-2xl px-6 py-6 '>
        {children}
        </div>
        <Footer/>
        </div>
        </body>
    </html>
  )
}
